# This workflow will install Python dependencies on Windows and run tests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Propylean on Windows

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: temurin
    - name: Install Spark
      uses: vemonet/setup-spark@v1
      with:
        spark-version: '3.5.3'
        hadoop-version: '3'
    - run: spark-submit --version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        python -m pip install thermo
        python -m pip install fluids
        python -m pip install pandas
        python -m pip install build
        python -m pip install pyspark
        python -m pip install tabulate
        python -m pip uninstall -y numpy
        python -m pip install numpy==1.26.4
        python -m pip install pyarrow
    - name: Install Propylean
      run: |
        git clone https://github.com/abhishekvraman/Propylean.git
        cd Propylean
        python -m build
        python -m pip install dist/propylean-0.3.0-py3-none-any.whl
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest tests
